"""updates Cat model to add pet_count

Revision ID: 434c6e2c7e6c
Revises: 20cbdad7decd
Create Date: 2022-12-13 10:48:00.251435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434c6e2c7e6c'
down_revision = '20cbdad7decd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('pet_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'pet_count')
    # ### end Alembic commands ###
